# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-24 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('times', models.CharField(max_length=30, verbose_name='时间')),
                ('body', models.TextField(max_length=1000, verbose_name='正文')),
                ('blogs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.User')),
            ],
        ),
    ]
