# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-24 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='blogs',
            new_name='blog_info',
        ),
    ]
