# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-24 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180724_0743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='blog_info',
            new_name='bu',
        ),
    ]
